apiVersion: apps/v1
kind: Deployment
metadata:
  name: asreview-worker
  namespace: asreview-cloud
spec:
  replicas: 8
  selector:
    matchLabels:
      app: asreview-worker
  template:
    metadata:
      labels:
        app: asreview-worker
    spec:
      containers:
        - name: c
          image: abelsiqueira/worker
          resources:
            limits:
              memory: "4Gi"
              cpu: "1"
          volumeMounts:
            - name: asreview-storage
              mountPath: /app/workdir
          env:
            - name: RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: username
            - name: RABBITMQ_PASS
              valueFrom:
                secretKeyRef:
                  name: rabbitmq-default-user
                  key: password
            - name: RABBITMQ_HOST
              value: rabbitmq
            - name: RABBITMQ_PORT
              value: "5672"
            # - name: S3_REGION_NAME
            #   valueFrom:
            #     secretKeyRef:
            #       name: s3-secret
            #       key: S3_REGION_NAME
            # - name: S3_ENDPOINT_URL
            #   valueFrom:
            #     secretKeyRef:
            #       name: s3-secret
            #       key: S3_ENDPOINT_URL
            # - name: S3_AWS_ACCESS_KEY_ID
            #   valueFrom:
            #     secretKeyRef:
            #       name: s3-secret
            #       key: S3_AWS_ACCESS_KEY_ID
            # - name: S3_AWS_SECRET_ACCESS_KEY
            #   valueFrom:
            #     secretKeyRef:
            #       name: s3-secret
            #       key: S3_AWS_SECRET_ACCESS_KEY
      restartPolicy: Always
      volumes:
        - name: asreview-storage
          # nfs:
          #   server: <FIXME>
          #   path: "/"
          # persistentVolumeClaim:
          #   claimName: asreview-storage
